spring:
  datasource:
    url: jdbc:${MYSQL_URL:mysql://localhost:3306/spring_security}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:Vs368797@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true

jwt:
  key: 'x&F:?061+<=},:3F]BEOHSVZDqb<+pqg#pJKx"JBZnOl;>|`PR7#-Fga{&G~MZ!b[On1c]5IF0y9pWa_5q~sGGa:x1Gg8Ar..2]pGWL8W"QyrRZo+wkRDtH8tx5Cb/M%Z2")XA!(VCu|t0gKf8o%U@q]clbzdev]$ChGiw=/0D?I98R-HIdZE-7+Gl"Y[cg{J*B4l6F?lShmvtFGqTvf1:i7~]DAbz{y]w_xtq{QSH2>)oOqO`THIX}jUH_YstBr;:PBp8-nuTud#4X*(.+>5@pcy@"1C_5}H}$eO$nxT@^pF+W6mDv5cQa}MDKzf@w)$,W@nTEr7|d(&2FH6IQY'
  expirationTime: 1800000